language: node_js
branches:
  only:
    - master
node_js:
  - "12"
  - "10"
  - "8"
env:
  - NODE_TLS_REJECT_UNAUTHORIZED=0 INTRAVENOUS=yes
services: mongodb
script: "npm run-script test-cover"
after_success: "npm run report-coverage"
